name = "apps"
main = "index.js"
compatibility_date = "2026-03-20"

[assets]
directory = "./client/dist"
# This tells Cloudflare to serve index.html if a route (like /dashboard) isn't found
not_found_handling = "single-page-application"